global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'kisaragi scraper'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['kisaragi-core.herokuapp.com']
